-- En este archivo deben estar tus ejercicios de consultas sql

-- 1)
SELECT NOMBRES 
FROM EMPLEADOS 
ORDER BY NOMBRES DESC;

-- 2)
SELECT E.NOMBRES, P.PUESTO, L.LOCALIDAD 
FROM EMPLEADOS E
INNER JOIN PUESTOS P ON E.PUESTO_ID = P.ID
INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE P.PUESTO = 'Soporte';

-- 3)
SELECT NOMBRES 
FROM EMPLEADOS 
WHERE NOMBRES LIKE '%o';

-- 4)
SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Carlos Paz';

-- 5)
SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE E.SUELDO BETWEEN 10000 AND 13000;

-- 6)
SELECT D.NOMBRE, COUNT(E.ID) AS CANTIDAD_EMPLEADOS
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
GROUP BY D.NOMBRE
HAVING COUNT(E.ID) > 5;

-- 7)
SELECT E.NOMBRES
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
INNER JOIN PUESTOS P ON E.PUESTO_ID = P.ID
WHERE L.LOCALIDAD = 'Córdoba' AND (P.PUESTO = 'Analista' OR P.PUESTO = 'Programador');

-- 8)
SELECT AVG(SUELDO) AS SUELDO_MEDIO
FROM EMPLEADOS;

-- 9)
SELECT MAX(SUELDO) AS MAXIMO_SUELDO
FROM EMPLEADOS
WHERE DEPARTAMENTO_ID = 10;

-- 10)
SELECT MIN(SUELDO) AS MINIMO_SUELDO
FROM EMPLEADOS
INNER JOIN PUESTOS P ON EMPLEADOS.PUESTO_ID = P.ID
WHERE P.PUESTO = 'Soporte';

-- 11)
SELECT P.PUESTO, SUM(E.SUELDO) AS SUMA_SUELDOS
FROM EMPLEADOS E
INNER JOIN PUESTOS P ON E.PUESTO_ID = P.ID
GROUP BY P.PUESTO;